protocol=vless
address=address:
port=port:
flow=xtls-rprx-vision
id=id:
security=security:[tls,reality]
sni=sni:
serverName=sni
fp=fingerprint:[chrome,firefox,edge,safari,360,qq,ios,android,random,randomized]
allowInsecure=Skip certificate validation:[false,true]
publicKey=publicKey:
shortId=shortId:
multiplex=Multiplex:[false,true]